### ISSUE TITLE
How can I install vue-clampy?

### ISSUE THREAD

**Issue by joedawson** [clampy-js/vue-clampy#1]

**Comment by hvaughan3** [comment]
Check out the [NPM page](https://www.npmjs.com/package/@clampy-js/vue-clampy).

**Comment by joedawson** [comment]
@hvaughan3 I can install the package, it's actually setting up the directive that hasn't been documented.

**Comment by hvaughan3** [comment]
Should be like this:

    import clampy from '@clampy-js/vue-clampy'

    Vue.use(clampy)

And then check out the [example index.html](https://github.com/clampy-js/vue-clampy/blob/master/examples/index.html) file for how to add the attribute to an actual element.

**Comment by joedawson** [comment]
@hvaughan3 thank you, that worked perfectly.
